Fix LOC_CHECK_FUNC error message
git-svn-id: https://svn.osgeo.org/grass/grass/trunk@47301 15284696-431f-4ddb-bdfa-cd5b030d7da7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9855,7 +9855,7 @@ else
   echo "$ac_t""no" 1>&6
 
 
-{ echo "configure: error: *** Unable to locate ." 1>&2; exit 1; }
+{ echo "configure: error: *** Unable to locate glXCreatePbuffer." 1>&2; exit 1; }
 
 
 fi
@@ -9918,7 +9918,7 @@ else
   echo "$ac_t""no" 1>&6
 
 
-{ echo "configure: error: *** Unable to locate ." 1>&2; exit 1; }
+{ echo "configure: error: *** Unable to locate glXCreateGLXPixmap." 1>&2; exit 1; }
 
 
 fi
@@ -10054,7 +10054,7 @@ else
   echo "$ac_t""no" 1>&6
 
 
-{ echo "configure: error: *** Unable to locate glBegin." 1>&2; exit 1; }
+{ echo "configure: error: *** Unable to locate OpenGL library." 1>&2; exit 1; }
 
 
 
@@ -10117,7 +10117,7 @@ else
   echo "$ac_t""no" 1>&6
 
 
-{ echo "configure: error: *** Unable to locate gluBeginCurve." 1>&2; exit 1; }
+{ echo "configure: error: *** Unable to locate GLU library." 1>&2; exit 1; }
 
 
 
@@ -12980,7 +12980,7 @@ else
   echo "$ac_t""no" 1>&6
 
 
-{ echo "configure: error: *** Unable to locate ." 1>&2; exit 1; }
+{ echo "configure: error: *** Unable to locate cairo_create." 1>&2; exit 1; }
 
 
 fi
