CI: Post pre-commit fixes as suggestions (#6809)

diff --git a/.github/workflows/additional_checks.yml b/.github/workflows/additional_checks.yml
--- a/.github/workflows/additional_checks.yml
+++ b/.github/workflows/additional_checks.yml
@@ -25,6 +25,9 @@ jobs:
     runs-on: ubuntu-24.04
     permissions:
       contents: read
+    env:
+      # renovate: datasource=pypi depName=prek
+      PREK_VERSION: 0.2.24
 
     steps:
       - name: Checkout repository contents
@@ -50,7 +53,7 @@ jobs:
 
       - name: Generate core modules with last commit JSON file and test it
         run: |
-          python -m pip install pytest pytest-depends
+          python -m pip install pytest pytest-depends pytest-timeout
           python utils/generate_last_commit_file.py .
           pytest utils/test_generate_last_commit_file.py
 
@@ -64,20 +67,61 @@ jobs:
           python ./utils/generate_release_notes.py log \
               "${GITHUB_REF_NAME}" \
               "$(git rev-parse HEAD~30)" \
-              ""
-      - name: "Cache pre-commit"
+              "" | \
+            tee -a "release_notes_sample.md"
+      - name: Upload release notes and core modules with last commit JSON file
+        if: ${{ !cancelled() }}
+        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
+        with:
+          name: release_notes-core_modules_with_last_commit
+          path: |-
+            core_modules_with_last_commit.json
+            release_notes_sample.md
+      - name: Remove created files
+        run: rm --verbose -f release_notes_sample.md core_modules_with_last_commit.json
+      - name: "Cache pre-commit/prek"
         # Not used for releases, only for running pre-commit
         uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3  # zizmor: ignore[cache-poisoning]
         with:
-          path: ~/.cache/pre-commit
+          path: |-
+            ~/.cache/prek
           key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
-
-      - name: "Run pre-commit"
+      - name: Install prek
+        run: uv tool install "prek@${PREK_VERSION}"
+      - name: "Run pre-commit/prek for fixes"
         run: |
           echo '```console' > "$GITHUB_STEP_SUMMARY"
           # Enable color output for pre-commit and remove it for the summary
           # Use --hook-stage=manual to enable slower pre-commit hooks that are skipped by default
-          uvx pre-commit run --all-files --show-diff-on-failure --color=always --hook-stage=manual | \
+          # Skip hooks already handled in another workflow, to avoid duplicate suggestions
+          # Skip hooks with no fixes made with these hooks (for now)
+          prek run --all-files --show-diff-on-failure --color=always --hook-stage=manual \
+            --skip ruff-check --skip ruff-format \
+            --skip actionlint \
+            --skip editorconfig-checker \
+            --skip flake8 \
+            --skip yamllint | \
+            tee >(sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[mGK]//g' >> "$GITHUB_STEP_SUMMARY") >&1
+          exit_code="${PIPESTATUS[0]}"
+          echo '```' >> "$GITHUB_STEP_SUMMARY"
+          exit "$exit_code"
+
+      - name: Create and uploads code suggestions to apply for pre-commit
+        # Will fail fast here if there are changes required
+        id: diff-pre-commit
+        # To run after pre-commit step exits with failure
+        if: ${{ !cancelled() }}
+        uses: ./.github/actions/create-upload-suggestions
+        with:
+          tool-name: pre-commit
+          # To keep repo's file structure in formatted changes artifact
+          extra-upload-changes: pyproject.toml
+      - name: "Run pre-commit/prek"
+        run: |
+          echo '```console' > "$GITHUB_STEP_SUMMARY"
+          # Enable color output for pre-commit and remove it for the summary
+          # Use --hook-stage=manual to enable slower pre-commit hooks that are skipped by default
+          prek run --all-files --show-diff-on-failure --color=always --hook-stage=manual | \
             tee >(sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[mGK]//g' >> "$GITHUB_STEP_SUMMARY") >&1
           exit_code="${PIPESTATUS[0]}"
           echo '```' >> "$GITHUB_STEP_SUMMARY"
